# Generated by Django 4.0.6 on 2022-07-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_image_options_alter_image_order_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='order_number',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Порядковый номер'),
        ),
    ]
